# Generated by Django 6.0.1 on 2026-02-13 07:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotebookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='notebooks/images')),
                ('base_description', models.TextField(blank=True, help_text='General description for all variants')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='nawaPuspanjali.brand')),
                ('notebook_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='nawaPuspanjali.notebooktype')),
            ],
            options={
                'ordering': ['brand__name', 'notebook_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotebookVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('variant_description', models.TextField(blank=True, help_text='Additional details specific to this size/ruling combination')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='nawaPuspanjali.notebook')),
                ('ruling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_variants', to='nawaPuspanjali.ruling')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_variants', to='nawaPuspanjali.size')),
            ],
            options={
                'verbose_name': 'Notebook Variant',
                'verbose_name_plural': 'Notebook Variants',
                'ordering': ['notebook', 'size__display_order', 'ruling__name'],
            },
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['brand', 'notebook_type'], name='nawaPuspanj_brand_i_4d0b92_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['is_active'], name='nawaPuspanj_is_acti_2c5d6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together={('name', 'brand', 'notebook_type')},
        ),
        migrations.AddIndex(
            model_name='notebookvariant',
            index=models.Index(fields=['notebook', 'size', 'ruling'], name='nawaPuspanj_noteboo_2c50ae_idx'),
        ),
        migrations.AddIndex(
            model_name='notebookvariant',
            index=models.Index(fields=['is_active'], name='nawaPuspanj_is_acti_b6ee96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notebookvariant',
            unique_together={('notebook', 'size', 'ruling')},
        ),
    ]
