# Generated by Django 6.0.1 on 2026-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaPuspanjali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookvariant',
            name='gsm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
