# Generated by Django 6.0.1 on 2026-02-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaPuspanjali', '0002_notebookvariant_gsm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebooktype',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='notebooktype',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
