# Generated by Django 6.0.1 on 2026-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaPuspanjali', '0003_alter_notebooktype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='size',
            name='unit',
            field=models.CharField(choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('in', 'Inches')], default='mm', max_length=10),
        ),
        migrations.AddField(
            model_name='size',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
