# Generated by Django 6.0.1 on 2026-02-15 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nawaPuspanjali', '0004_size_height_size_unit_size_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
